from sqlalchemy import Column, Integer, String, Text, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from app.database import Base


class Profile(Base):
    __tablename__ = "profiles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    email = Column(String, unique=True, nullable=False)
    mobile_number = Column(String, nullable=True)
    professional_title = Column(String, nullable=True)
    location = Column(String, nullable=True)
    professional_bio = Column(Text, nullable=True)
    job_alerts = Column(Boolean, default=False)
    linkedin_profile = Column(String, nullable=True)
    portfolio_website = Column(String, nullable=True)
    github_profile = Column(String, nullable=True)
    profile_image = Column(String, nullable=True)
    job_titles = Column(String, nullable=True)
    work_type = Column(String, nullable=True)
    current_salary = Column(String, nullable=True)
    expected_salary = Column(String, nullable=True)
    availability_start = Column(String, nullable=True)
    relocate = Column(Boolean, default=False)
    remote = Column(Boolean, default=False)
    hybrid = Column(Boolean, default=False)
    company_name = Column(String, nullable=True)
    job_title = Column(String, nullable=True)
    job_location = Column(String, nullable=True)
    start_date = Column(String, nullable=True)
    end_date = Column(String, nullable=True)
    currently_working = Column(Boolean, default=False)
    responsibilities = Column(Text, nullable=True)
    skills = Column(String, nullable=True)
    education_level = Column(String, nullable=True)
    field_of_study = Column(String, nullable=True)
    college_name = Column(String, nullable=True)
    edu_start_year = Column(String, nullable=True)
    edu_end_year = Column(String, nullable=True)
    currently_studying = Column(Boolean, default=False)
    resume_skills = Column(String, nullable=True)
    resume_file = Column(String, nullable=True)
    certificate_name = Column(String, nullable=True)
    issuing_org = Column(String, nullable=True)
    issue_date = Column(String, nullable=True)
    expiry_date = Column(String, nullable=True)
    credential_url = Column(String, nullable=True)
    project_name = Column(String, nullable=True)
    technologies = Column(String, nullable=True)
    project_description = Column(Text, nullable=True)
    project_link = Column(String, nullable=True)
    project_image_url = Column(String, nullable=True)

    user = relationship("User", back_populates="profile")
